### ISSUE TITLE
Jcanvas Draw Image Vs Draw Text

### ISSUE THREAD

**Issue by sreenathnemenon** [caleb531/jcanvas-website#3]
I tried to draw an image using draw image and i need to show a label for the image.So i choose drawtext. I had set x and y as same for both . But text is writing away from the image.Even though the x and y are showing the same as image.

**Comment by caleb531** [comment]
Hi, @sreenathnemenon. Could you please provide a code snippet that reproduces your issue? Something I can run in the [jCanvas Sandbox](https://projects.calebevans.me/jcanvas/sandbox/) would be ideal.

**Comment by sreenathnemenon** [comment]
Hi @caleb531 
https://projects.calebevans.me/jcanvas/sandbox/

To recreate the issue just change the y value from 150 for both to 300. Then you can see the distance between the image and text  is increasing.

**Comment by caleb531** [comment]
@sreenathnemenon Sorry, you can't share Sandbox links like you used to (they were extremely long and many programs did not accept them). Can you please post the actual code from that demo here (in this issue)? Thanks for your patience.

**Comment by sreenathnemenon** [comment]
@caleb531 I ope that issue got fixed. To day i done it as first draw the text then the image then it done correctly.Thanks.

**Comment by caleb531** [comment]
Yes, @sreenathnemenon, this bug was actually reported in https://github.com/caleb531/jcanvas/issues/290 a day after you submitted this issue. I didn't realize they were connected until now, but I was able to work out a fix and release it in jCanvas v20.1.0.
