### ISSUE TITLE
setEventHooks() for mouse events?

### ISSUE THREAD

**Issue by Ahaenor** [caleb531/jcanvas-website#4]
Hello,

I have a single canvas with several mouse-interactive layers on it. I'd like to register a single callback to handle each event type (click, mouseover, mouseout). The alternative - registering 3 callbacks for each layer - works, but it tooks a great toll on performance.

I'm trying to use setEventHooks() like this:

```
$('#my-canvas').setEventHooks({
		click: function( layer ) {
			console.log(layer);
			$(this).animateLayer( layer, {
				strokeWidth: '+=4',
                                radius: '+=4'
		        }, 100 );
		}
});
```

But it's not working. The browser console also doesn't show anything.

The "add" callback registration works normally, but I'm interested specifically in mouse events processing.

I'm using jQuery 1.12.4 and jCanvas 20.1.4 from CDN.

What may be the reason?

**Comment by caleb531** [comment]
@Ahaenor Event hooks fire only when the canvas is redrawn, and the click event is only bound to the canvas when a layer has a click event on it (I'd need to update the code to perform this binding for setEventHooks as well). For now, you can try adding:

```
$('#my-canvas').on('click', function() {
  $(this).drawLayers();
});
```

**Comment by Ahaenor** [comment]
OK, thanks for the quick answer. The code doesn't work, though(
We'll be waiting for the setEventHooks() update.

**Comment by caleb531** [comment]
@Ahaenor, so I realized that my current code in the jCanvas source for triggering an event hook requires a layer to call the initial event on.

This highlights a problem with your attempt to solve this problem: how will jCanvas know to fire your `click` event hook if you haven't specified which layers are clickable? You might as well just bind a jQuery `click` event to the whole canvas:

```js
$('canvas').on('click', function () {
  // do stuff here
});
```

Alternatively, I realized that if you want to designate some layers as clickable, you can simply set any layer's `click` callback to the same dummy function, and the `click` event hook will still get called as you desire. See the following example, which you can test in the [jCanvas Sandbox](https://projects.calebevans.me/jcanvas/sandbox/):

```js
var $canvas = $('canvas');

$canvas.setEventHooks({
  click: function() {
    alert(1);
  }
});
var dummyClick = function() {};

$canvas.drawArc({
  layer: true,
  click: dummyClick,
  fillStyle: '#c33',
  x: 100, y: 100,
  radius: 50
});
$canvas.drawArc({
  layer: true,
  // Comment the below line out to
  // disable clicking for this layer
  click: dummyClick,
  fillStyle: '#36c',
  x: 100, y: 250,
  radius: 50
});
```

**Comment by Ahaenor** [comment]
OK, thanks.

30 дек. 2017 г. 22:08 пользователь "Caleb Evans" <notifications@github.com>
написал:
