### ISSUE TITLE
ZoomIn, ZoomOut - How?

### ISSUE THREAD

**Issue by the1bit** [caleb531/jcanvas-website#7]
Hi,

I am writing to ask your help. How I can make ZoomIn and ZoomOut for the whole canvas?
I tried to use the "scaleCanvas" method but it does not work well. When I start to decrease the scale property value it seem ok, but when I start to increase it the diagram size is smaller and smaller. 

```
function zoomDiagram(zoomDirection, canvasId) {
    if (canvasId) {
        switch (zoomDirection) {
            case 'in': {
                if (zoomPercent < 150) {
                    zoomPercent = zoomPercent + 5;
                    $("#zoomPercent").text(zoomPercent);
                }
                break;
            }
            case 'out': {
                if (zoomPercent > 10) {
                    zoomPercent = zoomPercent - 5;
                    $("#zoomPercent").text(zoomPercent);
                }
                break;
            }
        }
        let zoomValue = zoomPercent / 100;
        $("#" + canvasId).scaleCanvas({
            scale: zoomValue
        }).drawLayers({
            complete: function () {
                console.log('Layers Done');
            }
        });
    }
}
```

Could you please suggest a solution for that?

Thanks in advance.

**Comment by caleb531** [comment]
@the1bit Please check out my [jcanvas-panzoom-demo](https://github.com/caleb531/jcanvas-panzoom-demo) project. I've worked out all the math there for panning/zooming the canvas, and that's the logic you should follow.
